// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/synapse/v1/sidecar.proto

package synapsev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	TtlSec        int32                  `protobuf:"varint,7,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *PublishRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PublishRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *PublishRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

type PublishBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Events        []*PublishRequest      `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchRequest) Reset() {
	*x = PublishBatchRequest{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchRequest) ProtoMessage() {}

func (x *PublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchRequest.ProtoReflect.Descriptor instead.
func (*PublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *PublishBatchRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *PublishBatchRequest) GetEvents() []*PublishRequest {
	if x != nil {
		return x.Events
	}
	return nil
}

type PublishBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryIds      []string               `protobuf:"bytes,1,rep,name=entry_ids,json=entryIds,proto3" json:"entry_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchResponse) Reset() {
	*x = PublishBatchResponse{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchResponse) ProtoMessage() {}

func (x *PublishBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchResponse.ProtoReflect.Descriptor instead.
func (*PublishBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBatchResponse) GetEntryIds() []string {
	if x != nil {
		return x.EntryIds
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	BatchSize     int32                  `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *SubscribeRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	EntryId       string                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Event) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	EntryIds      []string               `protobuf:"bytes,3,rep,name=entry_ids,json=entryIds,proto3" json:"entry_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *AckRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AckRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *AckRequest) GetEntryIds() []string {
	if x != nil {
		return x.EntryIds
	}
	return nil
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acked         int32                  `protobuf:"varint,1,opt,name=acked,proto3" json:"acked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *AckResponse) GetAcked() int32 {
	if x != nil {
		return x.Acked
	}
	return 0
}

type StreamInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfoRequest) Reset() {
	*x = StreamInfoRequest{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoRequest) ProtoMessage() {}

func (x *StreamInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoRequest.ProtoReflect.Descriptor instead.
func (*StreamInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *StreamInfoRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type StreamInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int64                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Groups        int32                  `protobuf:"varint,2,opt,name=groups,proto3" json:"groups,omitempty"`
	FirstEntryId  string                 `protobuf:"bytes,3,opt,name=first_entry_id,json=firstEntryId,proto3" json:"first_entry_id,omitempty"`
	LastEntryId   string                 `protobuf:"bytes,4,opt,name=last_entry_id,json=lastEntryId,proto3" json:"last_entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfoResponse) Reset() {
	*x = StreamInfoResponse{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoResponse) ProtoMessage() {}

func (x *StreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoResponse.ProtoReflect.Descriptor instead.
func (*StreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *StreamInfoResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StreamInfoResponse) GetGroups() int32 {
	if x != nil {
		return x.Groups
	}
	return 0
}

func (x *StreamInfoResponse) GetFirstEntryId() string {
	if x != nil {
		return x.FirstEntryId
	}
	return ""
}

func (x *StreamInfoResponse) GetLastEntryId() string {
	if x != nil {
		return x.LastEntryId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	RedisStatus   string                 `protobuf:"bytes,2,opt,name=redis_status,json=redisStatus,proto3" json:"redis_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_sidecar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetRedisStatus() string {
	if x != nil {
		return x.RedisStatus
	}
	return ""
}

var File_proto_synapse_v1_sidecar_proto protoreflect.FileDescriptor

const file_proto_synapse_v1_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/synapse/v1/sidecar.proto\x12\n" +
	"synapse.v1\"\xcc\x01\n" +
	"\x0ePublishRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x17\n" +
	"\attl_sec\x18\a \x01(\x05R\x06ttlSec\",\n" +
	"\x0fPublishResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"a\n" +
	"\x13PublishBatchRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x122\n" +
	"\x06events\x18\x02 \x03(\v2\x1a.synapse.v1.PublishRequestR\x06events\"3\n" +
	"\x14PublishBatchResponse\x12\x1b\n" +
	"\tentry_ids\x18\x01 \x03(\tR\bentryIds\"\x95\x01\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\"\xa9\x01\n" +
	"\x05Event\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"h\n" +
	"\n" +
	"AckRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x1b\n" +
	"\tentry_ids\x18\x03 \x03(\tR\bentryIds\"#\n" +
	"\vAckResponse\x12\x14\n" +
	"\x05acked\x18\x01 \x01(\x05R\x05acked\"+\n" +
	"\x11StreamInfoRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\"\x8e\x01\n" +
	"\x12StreamInfoResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x03R\x06length\x12\x16\n" +
	"\x06groups\x18\x02 \x01(\x05R\x06groups\x12$\n" +
	"\x0efirst_entry_id\x18\x03 \x01(\tR\ffirstEntryId\x12\"\n" +
	"\rlast_entry_id\x18\x04 \x01(\tR\vlastEntryId\"\x0f\n" +
	"\rHealthRequest\"M\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fredis_status\x18\x02 \x01(\tR\vredisStatus2\xad\x03\n" +
	"\x0eSynapseSidecar\x12B\n" +
	"\aPublish\x12\x1a.synapse.v1.PublishRequest\x1a\x1b.synapse.v1.PublishResponse\x12Q\n" +
	"\fPublishBatch\x12\x1f.synapse.v1.PublishBatchRequest\x1a .synapse.v1.PublishBatchResponse\x12>\n" +
	"\tSubscribe\x12\x1c.synapse.v1.SubscribeRequest\x1a\x11.synapse.v1.Event0\x01\x126\n" +
	"\x03Ack\x12\x16.synapse.v1.AckRequest\x1a\x17.synapse.v1.AckResponse\x12K\n" +
	"\n" +
	"StreamInfo\x12\x1d.synapse.v1.StreamInfoRequest\x1a\x1e.synapse.v1.StreamInfoResponse\x12?\n" +
	"\x06Health\x12\x19.synapse.v1.HealthRequest\x1a\x1a.synapse.v1.HealthResponseB\x89\x01Z\x86\x01github.com/Team-Deepiri/deepiri-platform/platform-services/backend/deepiri-realtime-gateway/synapse-sidecar/proto/synapse/v1;synapsev1b\x06proto3"

var (
	file_proto_synapse_v1_sidecar_proto_rawDescOnce sync.Once
	file_proto_synapse_v1_sidecar_proto_rawDescData []byte
)

func file_proto_synapse_v1_sidecar_proto_rawDescGZIP() []byte {
	file_proto_synapse_v1_sidecar_proto_rawDescOnce.Do(func() {
		file_proto_synapse_v1_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_synapse_v1_sidecar_proto_rawDesc), len(file_proto_synapse_v1_sidecar_proto_rawDesc)))
	})
	return file_proto_synapse_v1_sidecar_proto_rawDescData
}

var file_proto_synapse_v1_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_synapse_v1_sidecar_proto_goTypes = []any{
	(*PublishRequest)(nil),       // 0: synapse.v1.PublishRequest
	(*PublishResponse)(nil),      // 1: synapse.v1.PublishResponse
	(*PublishBatchRequest)(nil),  // 2: synapse.v1.PublishBatchRequest
	(*PublishBatchResponse)(nil), // 3: synapse.v1.PublishBatchResponse
	(*SubscribeRequest)(nil),     // 4: synapse.v1.SubscribeRequest
	(*Event)(nil),                // 5: synapse.v1.Event
	(*AckRequest)(nil),           // 6: synapse.v1.AckRequest
	(*AckResponse)(nil),          // 7: synapse.v1.AckResponse
	(*StreamInfoRequest)(nil),    // 8: synapse.v1.StreamInfoRequest
	(*StreamInfoResponse)(nil),   // 9: synapse.v1.StreamInfoResponse
	(*HealthRequest)(nil),        // 10: synapse.v1.HealthRequest
	(*HealthResponse)(nil),       // 11: synapse.v1.HealthResponse
}
var file_proto_synapse_v1_sidecar_proto_depIdxs = []int32{
	0,  // 0: synapse.v1.PublishBatchRequest.events:type_name -> synapse.v1.PublishRequest
	0,  // 1: synapse.v1.SynapseSidecar.Publish:input_type -> synapse.v1.PublishRequest
	2,  // 2: synapse.v1.SynapseSidecar.PublishBatch:input_type -> synapse.v1.PublishBatchRequest
	4,  // 3: synapse.v1.SynapseSidecar.Subscribe:input_type -> synapse.v1.SubscribeRequest
	6,  // 4: synapse.v1.SynapseSidecar.Ack:input_type -> synapse.v1.AckRequest
	8,  // 5: synapse.v1.SynapseSidecar.StreamInfo:input_type -> synapse.v1.StreamInfoRequest
	10, // 6: synapse.v1.SynapseSidecar.Health:input_type -> synapse.v1.HealthRequest
	1,  // 7: synapse.v1.SynapseSidecar.Publish:output_type -> synapse.v1.PublishResponse
	3,  // 8: synapse.v1.SynapseSidecar.PublishBatch:output_type -> synapse.v1.PublishBatchResponse
	5,  // 9: synapse.v1.SynapseSidecar.Subscribe:output_type -> synapse.v1.Event
	7,  // 10: synapse.v1.SynapseSidecar.Ack:output_type -> synapse.v1.AckResponse
	9,  // 11: synapse.v1.SynapseSidecar.StreamInfo:output_type -> synapse.v1.StreamInfoResponse
	11, // 12: synapse.v1.SynapseSidecar.Health:output_type -> synapse.v1.HealthResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_synapse_v1_sidecar_proto_init() }
func file_proto_synapse_v1_sidecar_proto_init() {
	if File_proto_synapse_v1_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_synapse_v1_sidecar_proto_rawDesc), len(file_proto_synapse_v1_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_synapse_v1_sidecar_proto_goTypes,
		DependencyIndexes: file_proto_synapse_v1_sidecar_proto_depIdxs,
		MessageInfos:      file_proto_synapse_v1_sidecar_proto_msgTypes,
	}.Build()
	File_proto_synapse_v1_sidecar_proto = out.File
	file_proto_synapse_v1_sidecar_proto_goTypes = nil
	file_proto_synapse_v1_sidecar_proto_depIdxs = nil
}
